export default [
  {
    id: 0,
    username: 'string0',
    first_name: 'string0',
    last_name: 'string0',
    password: 'string',
    is_active: true,
    last_login: '2020-06-17T07:33:15.909Z',
    is_superuser: true,
  },
  {
    id: 2,
    username: 'Georg',
    first_name: 'string2',
    last_name: 'string2',
    password: 'string',
    is_active: true,
    last_login: '2020-06-17T07:33:15.909Z',
    is_superuser: true,
  },
  {
    id: 1,
    username: 'oleg',
    first_name: 'string1',
    last_name: 'string1',
    password: 'string',
    is_active: true,
    last_login: '2020-06-17T07:33:15.909Z',
    is_superuser: true,
  },
  {
    id: 4,
    username: 'strelok',
    first_name: 'string1',
    last_name: 'string1',
    password: 'string',
    is_active: true,
    last_login: '2020-06-17T07:33:15.909Z',
    is_superuser: true,
  },
  {
    id: 3,
    username: 'harrypotter',
    first_name: 'string1',
    last_name: 'string1',
    password: 'string',
    is_active: true,
    last_login: '2020-06-17T07:33:15.909Z',
    is_superuser: true,
  },
  {
    id: 5,
    username: 'bob',
    first_name: 'string1',
    last_name: 'string1',
    password: 'string',
    is_active: true,
    last_login: '2020-06-17T07:33:15.909Z',
    is_superuser: true,
  },
  {
    id: 6,
    username: 'bfg9000',
    first_name: 'string1',
    last_name: 'string1',
    password: 'string',
    is_active: true,
    last_login: '2020-06-17T07:33:15.909Z',
    is_superuser: true,
  },
]
